spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}


  jpa:
    open-in-view: true
#    hibernate:
#     ddl-auto: update


#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false

    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      globally_quoted_identifiers: true # 예약어
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect


  logging:
    level:
      org.springframework: DEBUG

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            - profile_nickname
            - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  batch:
    job:
      enable: false #true :  애플리케이션 실행 시 등록된 Job을 실행
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always




jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 3600000
  refresh-token-validity-in-seconds: 1209600000
